### PR TITLE
ci: Use downstream tmt plans

### PR DESCRIPTION
**Pull request by LecrisUT**
This one depends on a few upstream PRs:
- https://github.com/packit/tmt-plans/pull/8
- https://github.com/packit/packit/pull/2106

### CODE REVIEW

**Comment by LecrisUT** [comment]
I'm confused why the tmt tests are passing now even though the PRs above didn't land.

/packit test

**Comment by henryiii** [comment]
Main branch seems to be passing now, still needed?

**Comment by LecrisUT** [comment]
Yeah, it will be less maintainence in the long-run. Probably next week one of the bug-fixes will land and we can merge this.

**Comment by LecrisUT** [comment]
This one is ready for merging

**Comment by LecrisUT** [comment]
Oh, interesting, I will report the current testing-farm failure upstream. Can ignore it otherwise

**Comment by LecrisUT** [comment]
Made this a draft until https://github.com/packit/tmt-plans/pull/7 is merged and I remove d825a08e2918c02928d90558b40466899d44731f commit. Just want to test that these tests are resolved with the recent fixes upstream

**Review by henryiii — APPROVED** [review]

**Pull request merged**
