### PR TITLE
fix: use dev version of FindPython

### LINKED ISSUE #148: Custom FindPython backport
We'll need to get a more recent version of FindPython, and apply some of the patches found in https://gitlab.kitware.com/vtk/vtk/-/blob/master/CMake/patches/3.23/FindPython/Support.cmake .

### PR DESCRIPTION
**Pull request by henryiii**
This is now a port, see https://gitlab.kitware.com/cmake/cmake/-/issues/24185. Based on VTK's port at https://gitlab.kitware.com/vtk/vtk/-/blob/master/CMake/patches/3.23/FindPython/Support.cmake.

Support for the correct SOABI on PyPy and the Stable ABI are included.

Closes #148.

### CODE REVIEW

**Comment by henryiii** [comment]
```
CMake Error at C:/Users/runneradmin/AppData/Local/Temp/tmpr2c79_me/build/CMakeFiles/CMakeScratch/TryCompile-1a28id/CMakeLists.txt:2 (set):
  Syntax error in cmake code at

    C:/Users/runneradmin/AppData/Local/Temp/tmpr2c79_me/build/CMakeFiles/CMakeScratch/TryCompile-1a28id/CMakeLists.txt:2

  when parsing string

    C:\hostedtoolcache\windows\Python\3.11.0\x64\Lib\site-packages\scikit_build_core\resources\find_python

  Invalid character escape '\h'.
```

The slashes are backwards in try-compile.

**Comment by LecrisUT** [comment]
Maybe some cmake code needs to be passed through [`cmake_path`](https://cmake.org/cmake/help/latest/command/cmake_path.html) or on python side?

**Comment by henryiii** [comment]
@jcfr, @thewtex would you like to check this - specifically fa987eb. This applies the one relevant change in VTK's port, and a couple of changes based on usage of new features.

**Comment by jcfr** [comment]
Thanks for working on this 🙏

I should be able to review in the few days👌

**Comment by henryiii** [comment]
Okay, great. Let me know if you have any ideas for extra ways to test it; I'm already doing some basic testing, but it's not checking all paths through this file (and I think quite a few paths may never get hit due to the way we use this always knowing what Python interpreter we want). If it looks reasonable, it can go in - next version will be 0.2.

**Comment by henryiii** [comment]
Let's go ahead and put this in, and then it can be tweaked and adjusted later. I'd like to lean towards release early, release often, and get at least an dev release out for people to try in the next few days.

**Pull request merged**
