### PR TITLE
[Do not merge] Try python 3.13 on fedora

### PR DESCRIPTION
**Pull request by LecrisUT**
This is just to track the status of python 3.13. @henryiii I believe you have some additional features like freethreading from there that you want tested?

Blocked by:
- ~~pip [24.0](https://copr.fedorainfracloud.org/coprs/g/python/python3.13/package/python-pip/) < 24.1~b1~~ Submitted a build from [my fork](https://src.fedoraproject.org/fork/lecris/rpms/python-pip/tree/pip-24.1)
- ~~cattrs~~ -> ~~[immutables](https://bugzilla.redhat.com/show_bug.cgi?id=2246142)~~, ~~[sphinx](https://bugzilla.redhat.com/show_bug.cgi?id=2271405)~~

### CODE REVIEW

**Comment by henryiii** [comment]
See https://github.com/scikit-build/scikit-build-core/blob/37d17728226d9b335545c801db668fec6c5c4908/.github/workflows/ci.yml#L189 for (our only so far) example.

**Comment by LecrisUT** [comment]
So probably would need to re-run `%{pytest}` with the different executable. Hmm will look into that once the build dependencies are satisfied

**Comment by henryiii** [comment]
I don't think we have a free-threading test yet, we've used https://github.com/scikit-build/scikit-build-sample-projects/tree/main/projects/hello-free-threading so far. We should probably add a free-threading test here.

As for moving it, up to you. Do what is most helpful.

**Pull request closed without merging**
