### PR TITLE
fix: docs build

### PR DESCRIPTION
**Pull request by LecrisUT**
https://github.com/pypa/setuptools/pull/4023 Fixes the issue

### CODE REVIEW

**Comment by henryiii** [comment]
Fixed for now in #473. We'll need to remember to uncap that when setuptools gets fixed.

**Comment by LecrisUT** [comment]
Can you check c5defb8eb869cbb4e680445b5d7c79e9fa024199? That's a different fix

**Comment by henryiii** [comment]
This didn't fix it? I see the same error in CI. Though, looking at it, I do think this is better, since this is actually not the package name, but the import name.

**Comment by LecrisUT** [comment]
Yeah, it's not a fix of the CI or anything, but just a leftover reference from when the project name got changed.

**Comment by henryiii** [comment]
It always was scikit-build-core, it's just a mixup confusing package name (which is normalized to dashes) with import name - and importlib uses import name. I assume this throws an import error and follows the alternate path always.

**Review by henryiii — APPROVED** [review]

**Comment by LecrisUT** [comment]
Wait, but the project name in `pyproject.toml` is underscored. Doesn't it use the name from there?

**Comment by henryiii** [comment]
`_`, `-`, and `.` are required to be equivalent for packages. [packaging.utils.canonicalize_name](https://github.com/pypa/packaging/blob/7e68d828f265ef05cf4cd3b5def9baffef8c2968/src/packaging/utils.py#L43) converts them to dashes. So in theory, you should be able to choose your display name with some backends based on what you put in pyproject.toml, but that's the only effect. It seems that hatchling normalizes early in the process, so the display name has dashes no matter what. (I've always thought of it with dashes, so would change it if hatching started respecting dashes and dots for metadata).

**Comment by LecrisUT** [comment]
I remember an issue where I had to convert dashes to underscores, probably in `scikit-build`, but maybe the issue was with the sdist archive and not with pypi or other

**Comment by henryiii** [comment]
Yeah, we had some issues with normalization. They should be fixed in 0.5. Metadata should now respect whatever you enter, and the sdist name should be normalized to underscores.

**Pull request merged**
