### PR TITLE
feat: experimental support for editable installs

### PR DESCRIPTION
**Pull request by henryiii**
This is a very early implementation of editable mode. One mode is supported: redirect, which pulls the auto-discovered or manually specified Python package files from the source locations, and the binary files from the installed wheel. This method respects includes and ignores, but doesn't adjust automatically if new files are added.

A few planned changes:
- [x] `_editable.py` will be renamed and moved to resources.
- [x] configure return changes will be reverted (at least for now)
- [x] utils in wheel will be cleaned up a bit
- [x] dataclass will be removed from Finder (minimal import impact important)
- [x] A few unrelated changes will be pulled out into separate PR, #213
- [x] Consider name (rebuild might be an option, so "static" not ideal)
- [x] Add rebuild (opt in)
- [x] Check coverage support on editable installs (working with IMinuit)

For later:

- Include file extensions when converting modules
- Check datafile support

### CODE REVIEW

**Comment by LecrisUT** [comment]
> One mode is supported: static, which pulls the auto-discovered or manually specified Python package files from the source locations, and the binary files from the installed wheel.

> and the binary files from the installed wheel.

It doesn't handle libs yet right?

> manually specified Python package files 

Does this mean anything from the current source package folder? This does not link the additional library files like the python binding library file?

I think it would be helpful to have a pre-defined cmake build/install directory where we can run the cmake (e.g. from the ide) to rebuild from the original source, i.e. `cmake -B ./path/to/.scikit-build`. Maybe also create a `CMakePreset-scikit-build.json` so that it can be linked from a `CMakeUserPresets.json`.

**Comment by henryiii** [comment]
> It doesn't handle libs yet right?

I think it depends on how you load the lib. If you use `importlib.resources`, yes, if you manipulate file paths, no. But that's just an educated guess, not at all tested.

> Does this mean anything from the current source package folder? This does not link the additional library files like the python binding library file?

The things that CMake produces are put into the ephemeral wheel which is then installed into site packages. So the dir looks like:

```
<local>/src/mypackage/__init__.py
<env>/site-packages/mypackage/mylib.so
```

And `import mypackage` gets the first line, and `from mypackage import mylib` gets the second one. The import system combines the two physically different locations.

> I think it would be helpful to have a pre-defined cmake build/install directory where we can run the cmake

That's set with `tool.cmake.build-dir`, and the next step will be providing a way for the loader to rerun it as well. I hadn't thought about manually rerunning it, but that probably would work too. Might try that. The install target might be a little tricky, but I'm assuming meson-python has the final site-packages install target, so it should be doable.

I'd like to eventually have several methods, possibly including inplace builds & simple pth files, and certainly including meson-python's automatic rebuild (as an option).

I haven't worked with presets at all yet, will look into it eventually, also open to suggestions & info.

**Comment by LecrisUT** [comment]
> and `from mypackage import mylib` gets the second one.

Hmm, that would handle the python-C binder, but I wonder if it will also handle the linked library (assuming that the main C library is built as shared in this case), without manually specifying `LD_LIBRARY_PATH`. My suspicion is that as long as we instruct `cmake --install` to not strip `RPATH` and point it to the correct install path, it will automatically pick the correct library.

For the cmake preset, from my playing around with it, I think the minimum we need to define are:
- `configurePreset.binaryDir`: Point it to `tool.cmake.build-dir`. Might be tricky keeping `tool.cmake.build-dir` synchronized with this, but assuming these are always editted via `pip` commands, we could just re-create `CMakePreset-scikit-build.json` each time a `pip` command is passed, right?
- `configurePreset.cacheVariables.CMAKE_INSTALL_PREFIX`: Point it to the relevant site-package location. And similarly for any paths that need to be defined, `SKBUILD`, etc. This is where most of the magic happens. We can also add environment variables and so on.
- `buildPreset.targets`: Make sure it includes the relevant python target.
- Unfortunately there is [no `installPreset`](https://gitlab.kitware.com/cmake/cmake/-/issues/23208) where we can minimize to a specific component, so instead we can add `install` to `buildPreset.targets`. Not sure how to manipulate `RPath` in this case though.
- `workflowPreset`: Combine the `configure` and `build` steps
- If the user wants to update these, they should inherit the relevant presets and/or add a new `workflowPreset` (e.g. to add `ctest`) in their final `CMakeUserPresets.json` or the main `CMakePresets.json` that `include`s `CMakePreset-scikit-build.json`

**Comment by henryiii** [comment]
Okay, for an experimental first round of support, I think something like this will work. You have to opt-into the experimental live reloading explicitly, and live reloading probably won't work very well if you are relying on the backports and things.

I'll probably try to add a few tests of the live reloading, maybe some unit tests, and some docs, and clarify it's experimental (probably won't require the opt-in experimental flag, as it's a developer facing tool, not a user one, and that would be a lot of settings to have to pass on the command line).

The one thing I'm still looking into is the strange case were coverage isn't computed in CI but it is locally when I tried this with IMinuit.

**Comment by henryiii** [comment]
rpm-build caught that I missed `cmake3`. :)

**Comment by LecrisUT** [comment]
Sorry I didn't get to test this earlier, but I've found a usability issue. Not sure which part is causing this installation, but, after installing, there seems to be two copies of the python package. For example in `spglib`, there is a `venv/lib64/python3.11/site-packages/spglib/spglib.py` and a `venv/lib64/python3.11/site-packages/spglib.py`. Only the latter is re-installed at each import, but the former is the one actually being picked up. Shouldn't the former be a symlink to the latter? And just the confirm, the latter is the intended implementation that should be updated?

For reference here is the install instruction:
```cmake
set(Python_INSTALL_DIR ".")
install(TARGETS Spglib_symspg
	LIBRARY DESTINATION ${Python_INSTALL_DIR}
	PUBLIC_HEADER DESTINATION ${Python_INSTALL_DIR})
install(TARGETS Spglib_python
		LIBRARY DESTINATION ${Python_INSTALL_DIR})
install(DIRECTORY spglib/ DESTINATION ${Python_INSTALL_DIR})
```

**Comment by henryiii** [comment]
That's because it is picking up `/<package_name>` as a Python package and you are also installing the files manually. You shouldn't install Python files manually if possible - the auto-package discovery works better with editable mode (as the Python files don't get copied and stay editable). If you really want to copy them with CMake, you can disable the auto-discovery with `wheel.packages = []` (you can also list them explicitly here).

Symlinks are not allowed in editable mode, since editable installs via PEP 660 are based on a (temporary) whl, and whl is actually a zip, and Python has a many, many year old bug keeping it from handling a symlink in a zip file.

**Comment by LecrisUT** [comment]
You can try `main` https://github.com/spglib/spglib. I'll try again tomorrow with less explicit installation

**Comment by LecrisUT** [comment]
Ok, so all of the issues I reported here are solved with the appropriate packaging

**Pull request merged**
