### PR TITLE
fix: Ensure wheel.platlib being false sets <abi>-<platform> as "none-any"

### PR DESCRIPTION
**Pull request by jcfr**
* [x] Add regression test or update existing one

### CODE REVIEW

**Comment by jcfr** [comment]
This will be rebased once #657 is integrated :rocket:

**Comment by jcfr** [comment]
@henryiii This is pending review & approval :pray:

Once this is integrated, what do you think of releasing `0.8.2` ?

**Review by henryiii — APPROVED** [review]

**Comment by henryiii** [comment]
Very soon, a few more small fixes, but probably can plan on one by the weekend.

**Comment by jcfr** [comment]
In the meantime, thanks for the review

**Comment by henryiii** [comment]
Pushed 0.8.2.

**Pull request merged**
