### PR TITLE
feat: add `remove=` postprocess to regex

### LINKED ISSUE #765: Regex support for more complex structures?
Currently, something like this is hard to capture:

```cpp
#define NB_VERSION_MAJOR 2
#define NB_VERSION_MINOR 0
#define NB_VERSION_PATCH 1
#define NB_VERSION_DEV   1 // A value > 0 indicates a development release
```

As we only have a `{value}` field.

### PR DESCRIPTION
**Pull request by henryiii**
This adds the ability to post-process regex to remove "dev0" or similar. Closes #765.

### CODE REVIEW

**Comment by LecrisUT** [comment]
Was looking if this affects `SKBUILD_PROJECT_VERSION`
https://github.com/scikit-build/scikit-build-core/blob/6d2480f40570bcf4aed305acc9b907ccbb7b4025/src/scikit_build_core/builder/builder.py#L162
Shouldn't this one be [`.public`](https://packaging.pypa.io/en/latest/version.html#packaging.version.Version.public)? Fedora packaging uses the `1:a.b.c` format

**Comment by henryiii** [comment]
> The “base version” is the public version of the project without any pre or post release markers.

Isn't that what we want?

> 1:a.b.c

I think you mean `1!a.b.c`?

As to the epoch, it is included in both, which is probably not ideal for us, as CMake won't be able to understand an epoch.

**Comment by LecrisUT** [comment]
> > The “base version” is the public version of the project without any pre or post release markers.
> 
> Isn't that what we want?

There is an example of `public` and `base_version` when it comes to `epoch` in the link I posted last. I believe the `pre` and `post` there refer only to `suffix` part.

> > 1:a.b.c
> 
> I think you mean `1!a.b.c`?

Python wise, yes. Was just mentioning because there could be a synchronization between those that might be used (after changing `:` to `!` as needed)

**Comment by henryiii** [comment]
The examples are misleading, I've made https://github.com/pypa/packaging/pull/818 to clarify the examples. Both of them include the epoch. Generally, the epoch is the most important version number (more than even the major number), so that's probably why it's always included. We could easily avoid it by manually constructing the number, though, since CMake won't be able to parse it.

**Comment by LecrisUT** [comment]
Ah indeed, the code right beneath it makes it more obvious :D

**Pull request merged**
